module.exports = Object.freeze({
  MESSAGE_RECEIVED: 'MESSAGE_RECEIVED',
  MESSAGE_SENT: 'MESSAGE_SENT',
  SUBSCRIBED: 'SUBSCRIBED',
  UNSUBSCRIBED: 'UNSUBSCRIBED',
  CONVERSATION_STARTED: 'CONVERSATION_STARTED',
  ERROR: 'ERROR',
});
